# 중고 거래 게시물을 3건 이상 등록한 사용자의 사용자 ID, 닉네임, 전체주소, 전화번호
SELECT U.USER_ID, U.NICKNAME, 
       CONCAT(U.CITY," ",U.STREET_ADDRESS1," ",U.STREET_ADDRESS2) 전체주소, 
       CONCAT(LEFT(tlno,3), '-', MID(tlno,4,4),'-', RIGHT(tlno,4)) 전화번호
FROM USED_GOODS_USER U JOIN USED_GOODS_BOARD B ON B.WRITER_ID = U.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY U.USER_ID DESC