WITH TBL AS (
    SELECT C.DAILY_FEE, C.CAR_TYPE, H.HISTORY_ID,
           DATEDIFF(END_DATE, START_DATE) + 1 AS period,
    CASE 
      WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
      WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
      WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
      ELSE 'NONE' END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
INNER JOIN CAR_RENTAL_COMPANY_CAR AS C ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '트럭')   



SELECT TBL.HISTORY_ID, 
    ROUND(TBL.DAILY_FEE * TBL.period * 
          (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM TBL
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
    ON P.DURATION_TYPE = TBL.DURATION_TYPE 
    AND P.CAR_TYPE = TBL.CAR_TYPE
ORDER BY FEE DESC, TBL.HISTORY_ID DESC