# 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 
# 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력
# 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬

WITH TBL AS (
    SELECT C.DAILY_FEE, C.CAR_TYPE, H.HISTORY_ID,
           DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
    CASE 
      WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
      WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
      WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
      ELSE 'NONE' END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CAR_RENTAL_COMPANY_CAR AS C ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '트럭')   



SELECT TBL.HISTORY_ID, 
    ROUND(TBL.DAILY_FEE * TBL.PERIOD * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM TBL
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
    ON P.DURATION_TYPE = TBL.DURATION_TYPE 
    AND P.CAR_TYPE = TBL.CAR_TYPE
ORDER BY 2 DESC, 1 DESC